app:
  base_url: http://127.0.0.1:8000

browser:
  headless: false
  slow_mo: 200

mongodb:
  uri: "mongodb+srv://maheshdesu12_db_user:dRfBHuvqlTR85KEJ@cluster0.zi7s64o.mongodb.net/?appName=Cluster0"
  database: "ai_test_agent"
  collection: "users"

test_data:

  register:
    name: Test User
    email: user@example.com
    password: password123

  login:
    email: user@example.com
    password: password123